export const PRODUCT_CART = "PRODUCT_CART"
export const PRODUCT_CART_ICREMENT = "PRODUCT_CART_ICREMENT"
export const PRODUCT_CART_DECREMENT = "PRODUCT_CART_DECREMENT"
export const PRODUCT_CART_REMOVE = "PRODUCT_CART_REMOVE"
export const PRODUCT_CART_TOTAL_PRICE = "PRODUCT_CART_TOTAL_PRICE" 

