export const PRODUCT_CART = "PRODUCT_CART"
export const PRODUCT_CART_ICREMENT = "PRODUCT_CART_ICREMENT"
export const PRODUCT_CART_DECREMENT = "PRODUCT_CART_DECREMENT"
export const PRODUCT_CART_REMOVE = "PRODUCT_CART_REMOVE"
export const PRODUCT_CART_TOTAL_PRICE = "PRODUCT_CART_TOTAL_PRICE"
export const PRODUCT_CART_DATA = "PRODUCT_CART_DATA"
export const PRODUCT_CART_POPUP = "PRODUCT_CART_POPUP"
export const PRODUCT_CART_DELIVERY = "PRODUCT_CART_DELIVERY"
export  const PRODUCT_CART_DELIVERY_SUCCESS = "PRODUCT_CART_DELIVERY_SUCCESS"
export const PRODUCT_CART_DEFUALT_STATE = 'PRODUCT_CART_DEFUALT_STATE'

