
export const MAIN_ROUTE = 'MAIN_ROUTE'
export const PRODUCTS_DETAILS_ROUTE = 'PRODUCTS_DETAILS_ROUTE '
export const PRODUCTS_ORDER_ROUTE = "PRODUCTS_ORDER_ROUTE"
export const PRODUCT_MY_ORDER = "PRODUCT_MY_ORDER"
